/**
 * Static SpecialRegime + ExitRule definitions — single source of truth shared by
 * the full seed (seed.ts) and the targeted regime re-seed (seed-regimes.ts).
 *
 * Country is referenced by `countrySlug` (stable across DBs); the numeric
 * countryId is resolved at seed time from the DB via the country slug→id map.
 * Do not invent or alter values here — these mirror the legally researched data.
 */

export const regimeDefs = [
    {
      countrySlug: "pt", slug: "ifici-pt", nameDE: "IFICI / „NHR 2.0\" (Portugal)", nameEN: "IFICI / \"NHR 2.0\" (Portugal)",
      flatRate: 0.20, durationYears: 10,
      qualifications: ["Neuer PT-Steuerresident ab 1.1.2024", "In den letzten 5 Jahren kein PT-Steuerresident", "Nie zuvor das alte NHR genutzt", "Tätigkeit in Innovationsfeldern (Wissenschaft, Tech, Gesundheit, F&E); meist Hochschulabschluss EQF 6+", "Anerkennung über IAPMEI/AICEP"],
      conditionsDE: "20 % Pauschalsatz auf qualifizierte PT-Erwerbs-/Selbstständigeneinkünfte (statt progressiv bis 48 %). Die meisten ausländischen passiven Einkünfte sind befreit, wenn im Quellstaat besteuerbar (kein Blacklist-Land). Laufzeit 10 Jahre, nicht verlängerbar.",
      conditionsEN: "20% flat rate on qualifying PT employment/self-employment income (vs. progressive up to 48%). Most foreign passive income is exempt if taxable in the source state (no blacklist country). Duration 10 years, non-renewable.",
      validFrom: new Date("2024-01-01"), sourceUrl: "https://www.portaldasfinancas.gov.pt", sourceDE: "Portal das Finanças / AICEP / IAPMEI, IFICI 2024",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Offizielles portugiesisches Programm für Talente in Schlüsselsektoren. Antrag über Portal das Finanças. Einkünfte aus deutschen Quellen bleiben regulär steuerpflichtig. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "Official Portuguese programme for talent in key sectors. Apply via Portal das Finanças. Income from German sources remains taxable. Not binding advice, not tax counsel.",
      descriptionDE: "Nachfolger des alten NHR, offiziell „Incentivo Fiscal à Investigação Científica e Inovação\". Gezielt auf hochqualifizierte Talente in innovationsnahen Sektoren statt der breiten Begünstigung des Vorgängers.",
      descriptionEN: "Successor to the old NHR, officially the \"Incentivo Fiscal à Investigação Científica e Inovação\". Targeted at high-skill talent in innovation sectors rather than the broad benefit of its predecessor.",
      backgroundDE: "Wichtiger Unterschied zum Alt-NHR: Renten sind unter IFICI NICHT mehr befreit (Alt-NHR: 10 %). Das Alt-NHR ist für Neuanträge geschlossen (Stichtag 31.3.2025 für 2024-Zuzügler); bestehende NHR-Nutzer behalten ihre 10 Jahre. Abschaffung erfolgte wegen Missbrauchskritik und Immobilienpreis-Druck.",
      backgroundEN: "Key difference from old NHR: pensions are NO LONGER exempt under IFICI (old NHR: 10%). The old NHR is closed to new applicants (cut-off 31 Mar 2025 for 2024 arrivals); existing NHR holders keep their 10 years. Abolished over abuse criticism and property-price pressure.",
    },
    {
      countrySlug: "es", slug: "beckham-es", nameDE: "Beckham Law (Spanien)", nameEN: "Beckham Law (Spain)",
      flatRate: 0.24, durationYears: 6,
      qualifications: ["Zuzug aufgrund Arbeitsvertrag/Entsendung mit/zu spanischem Arbeitgeber", "In den letzten 5 Jahren kein ES-Steuerresident", "Antrag binnen 6 Monaten (Modelo 149)", "Seit 2023 auch: Digital-Nomad-Visum, Start-up-Gründer (<25 % Anteil), Ehepartner + Kinder <25", "NICHT: klassische Freelancer ohne Anstellung, Berufssportler"],
      conditionsDE: "24 % Pauschalsatz auf spanische Erwerbseinkünfte bis 600.000 €/Jahr (47 % darüber), statt progressiver IRPF (19–47 %). Ausländische Kapitaleinkünfte bleiben spanisch unbesteuert; Befreiung von Modelo 720. Gültig 6 Jahre (Ankunftsjahr + 5).",
      conditionsEN: "24% flat rate on Spanish employment income up to €600,000/yr (47% above), instead of progressive IRPF (19–47%). Foreign capital income stays untaxed in Spain; exemption from Modelo 720. Valid 6 years (arrival year + 5).",
      validFrom: new Date("2023-01-01"), sourceUrl: "https://sede.agenciatributaria.gob.es", sourceDE: "Agencia Tributaria (AEAT); Real Decreto 687/2005 / Ley IRPF",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Sozialabgaben laufen separat normal. Jahr-7-Klippe: danach volle Welteinkommens- und Vermögensbesteuerung — Planung 12–18 Monate vorher nötig. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "Social contributions run separately at normal rates. Year-7 cliff: full worldwide income and wealth taxation thereafter — plan 12–18 months ahead. Not binding advice, not tax counsel.",
      descriptionDE: "„Régimen especial de trabajadores desplazados\": besteuert zuziehende Arbeitnehmer wie Nicht-Residenten zum 24 %-Pauschalsatz statt der progressiven IRPF.",
      descriptionEN: "\"Régimen especial de trabajadores desplazados\": taxes inbound workers like non-residents at a 24% flat rate instead of progressive IRPF.",
      backgroundDE: "Benannt nach David Beckham (Real-Madrid-Transfer 2003). Seit 2023 durch das Digital-Nomad-Visum erweitert (Rechtsprechung 2025 bestätigt Angestellte ausländischer Firmen). Streit um fiktive Mieteinkünfte der Eigenwohnung (TEAC vs. TSJ Madrid 2025, ungeklärt).",
      backgroundEN: "Named after David Beckham (Real Madrid transfer 2003). Extended since 2023 to digital-nomad-visa holders (2025 case law confirmed employees of foreign firms). Dispute over deemed rental income on the own home (TEAC vs. TSJ Madrid 2025, unresolved).",
    },
    {
      countrySlug: "nl", slug: "ruling30-nl", nameDE: "Expat-Ruling (ehem. 30 %-Regeling, Niederlande)", nameEN: "Expat Ruling (formerly 30% Ruling, Netherlands)",
      flatRate: 0.3697, durationYears: 5,
      qualifications: ["Aus dem Ausland angeworben mit am NL-Markt knapper Expertise", "Steuerpflichtiges Mindestgehalt 48.013 € (2026, nach 30 %-Abzug; Unter-30 mit Master ~36.497 €)", "Begünstigung gedeckelt auf 262.000 € (2026); Satz bleibt 2026 bei 30 %, ab 2027 27 %"],
      conditionsDE: "Arbeitgeber zahlt einen Teil des Bruttolohns steuerfrei als Auslandskosten-Pauschale: 30 % (2025/2026), ab 1.1.2027 auf 27 % gesenkt. Max. 5 Jahre. Die geplante 30-20-10-Staffel wurde zurückgenommen.",
      conditionsEN: "Employer pays part of gross salary tax-free as a foreign-cost allowance: 30% (2025/2026), reduced to 27% from 1 Jan 2027. Max. 5 years. The planned 30-20-10 taper was reversed.",
      validFrom: new Date("2025-01-01"), sourceUrl: "https://www.belastingdienst.nl", sourceDE: "Belastingdienst / business.gov.nl 2025/2026",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Übergangsrecht: Wer das Ruling vor 1.1.2024 erstmals nutzte, behält günstigere Konditionen. Mindestgehaltsnorm gilt fortlaufend. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "Transitional rule: those who first used the ruling before 1 Jan 2024 keep more favourable terms. The salary norm applies continuously. Not binding advice, not tax counsel.",
      descriptionDE: "Erlaubt dem Arbeitgeber, einen festen Anteil des Bruttolohns steuerfrei als Pauschale für Auslandskosten auszuzahlen — soll die Niederlande für hochqualifizierte Migranten attraktiv halten.",
      descriptionEN: "Lets the employer pay a fixed share of gross salary tax-free as a flat allowance for foreign costs — designed to keep the Netherlands attractive to high-skill migrants.",
      backgroundDE: "2024 wegen Budget verschärft, dann teils zurückgedreht (27 % statt der Staffel). Auch Erstattung internationaler Schulgebühren möglich. Der Prozentwert ist eine Brutto-Freistellung, kein Steuersatz — der angezeigte Vergleichswert ist eine grobe Näherung.",
      backgroundEN: "Tightened in 2024 for budget reasons, then partly reversed (27% instead of the taper). International school-fee reimbursement also possible. The percentage is a gross exemption, not a tax rate — the comparison figure shown is a rough approximation.",
    },
    {
      countrySlug: "ee", slug: "ou-ee", nameDE: "Verteilte-Gewinn-Körperschaftsteuer / E-Residency OÜ (Estland)", nameEN: "Distributed-Profit CIT / E-Residency OÜ (Estonia)",
      flatRate: 0.22, durationYears: 99,
      qualifications: ["OÜ gegründet (ggf. über E-Residency)", "Gewinne werden erst bei Ausschüttung besteuert", "E-Residency ist KEIN Steuerstatus"],
      conditionsDE: "0 % Körperschaftsteuer auf einbehaltene/reinvestierte Gewinne, 22/78 (≈ 22 %) auf Ausschüttungen (der reduzierte Satz 14/86 wurde zum 1.1.2025 abgeschafft). Flache persönliche Einkommensteuer 22 % (seit 2025, vorher 20 %).",
      conditionsEN: "0% corporate tax on retained/reinvested profits, 22/78 (≈22%) on distributions (the reduced 14/86 rate was abolished on 1 Jan 2025). Flat personal income tax 22% (since 2025, previously 20%).",
      validFrom: new Date("2025-01-01"), sourceUrl: "https://www.emta.ee/en", sourceDE: "Maksu- ja Tolliamet (Estonian Tax and Customs Board) 2025",
      riskLevel: "high", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Hohes Risiko bei weiterhin deutschem Wohnsitz: volle deutsche Steuerpflicht (§ 49 EStG); E-Residency begründet keinen Steuerwohnsitz. Rechtliche Beratung dringend empfohlen. Keine verbindliche Auskunft.",
      disclaimerEN: "⚠ High risk if German residence is maintained: full German tax liability (§49 EStG); e-Residency does not establish tax residence. Legal advice strongly recommended. Not binding advice.",
      descriptionDE: "Unternehmensgewinne werden erst bei Ausschüttung besteuert (0 % auf einbehaltene Gewinne) — attraktiv für Gründer, die reinvestieren. Für Einzelpersonen gilt ein flacher ESt-Satz.",
      descriptionEN: "Company profits are taxed only on distribution (0% on retained earnings) — attractive for founders who reinvest. Individuals face a flat income-tax rate.",
      backgroundDE: "e-Residency ermöglicht die digitale Gründung/Verwaltung einer estnischen OÜ aus dem Ausland, ist aber kein Steuerstatus: maßgeblich bleibt der tatsächliche Wohn-/Geschäftsleitungssitz. Der angezeigte Satz (22 %) ist der Ausschüttungssatz.",
      backgroundEN: "e-Residency enables digital incorporation/management of an Estonian OÜ from abroad, but is not a tax status: actual residence / place of management governs. The displayed rate (22%) is the distribution rate.",
    },
    {
      countrySlug: "uae", slug: "zero-uae", nameDE: "0 % Einkommensteuer (VAE/Dubai)", nameEN: "0% Income Tax (UAE/Dubai)",
      flatRate: 0.00, durationYears: 99,
      qualifications: ["Wohnsitz in den VAE (Aufenthaltsvisum)", "Tatsächlicher Lebensmittelpunkt in den VAE", "Kein Einkommen aus deutschen Quellen (§ 49 EStG)"],
      conditionsDE: "0 % persönliche Einkommensteuer auf Gehalt oder Freelancer-Einkünfte. Keine Sozialabgaben für Expats. Seit 2023 jedoch 9 % Körperschaftsteuer ab Schwellen (für Gründer/Firmen relevant, für Angestellte nicht).",
      conditionsEN: "0% personal income tax on salary or freelance income. No social contributions for expats. Since 2023 however a 9% corporate tax above thresholds (relevant for founders/companies, not for employees).",
      validFrom: new Date("2000-01-01"), sourceUrl: "https://mof.gov.ae", sourceDE: "UAE Ministry of Finance",
      riskLevel: "high", requiresLegalAdvice: true,
      disclaimerDE: "⚠ KEIN aktives DBA mit Deutschland (seit 2021) → kein Schutz vor Doppelbesteuerung, erhöhtes Risiko bei fortbestehenden DE-Bindungen. § 4 AO: Scheinwohnsitz unterbricht deutsche Steuerpflicht nicht. Rechtliche Beratung erforderlich.",
      disclaimerEN: "⚠ NO active tax treaty with Germany (since 2021) → no protection from double taxation, elevated risk where German ties remain. §4 AO: a fictitious domicile does not end German tax liability. Legal advice required.",
      descriptionDE: "Keine Einkommensteuer ist hier die Grundregel, kein beantragbares Sonderregime. Netto = Brutto für Erwerbseinkünfte.",
      descriptionEN: "No income tax is the baseline rule here, not an applied-for special regime. Net = gross for earned income.",
      backgroundDE: "Kritischer DE-Bezug: Wegzug in die VAE ist steuerlich besonders riskant, weil das DBA seit 2021 ausgelaufen ist. In Kombination mit § 2 AStG (erweiterte beschränkte Steuerpflicht) und § 6 AStG (Wegzugsbesteuerung) zwingend Beratung.",
      backgroundEN: "Critical German angle: relocating to the UAE is especially risky for tax because the treaty lapsed in 2021. Combined with §2 AStG (extended limited liability) and §6 AStG (exit tax), advice is essential.",
    },
    {
      countrySlug: "ge", slug: "small-business-ge", nameDE: "Small Business Status (Georgien)", nameEN: "Small Business Status (Georgia)",
      flatRate: 0.01, durationYears: 99,
      qualifications: ["Registrierung als Einzelunternehmer (Individual Entrepreneur) mit Small Business Status", "Jahresumsatz unter 500.000 GEL", "Einkommen mit georgischer Quelle (Leistung i. d. R. in Georgien erbracht)"],
      conditionsDE: "1 % Steuer auf den Umsatz statt 20 % Einkommensteuer (3 % auf den Teil über 500.000 GEL im Jahr). Georgien besteuert territorial — ausländisch erzielte Einkünfte oft steuerfrei. Monatliche Steuererklärung Pflicht.",
      conditionsEN: "1% turnover tax instead of 20% income tax (3% on the part above 500,000 GEL per year). Georgia taxes territorially — foreign-source income often tax-free. Monthly tax return mandatory.",
      validFrom: new Date("2018-01-01"), sourceUrl: "https://www.rs.ge/en", sourceDE: "Revenue Service of Georgia 2025",
      riskLevel: "high", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Kein DBA mit Deutschland. Bei Beibehaltung des deutschen Wohnsitzes oder wesentlicher wirtschaftlicher Bindung: volle deutsche Steuerpflicht trotz 1 %-Regime. Status wird bei zweijähriger Überschreitung der Schwelle entzogen. Rechtliche Beratung erforderlich.",
      disclaimerEN: "⚠ No tax treaty with Germany. If German residence or material economic ties remain: full German tax liability despite the 1% regime. Status is revoked after two years over the threshold. Legal advice required.",
      descriptionDE: "Sehr relevant für Freelancer/Nomaden: Einzelunternehmer mit Small Business Status zahlen nur 1 % auf den Umsatz. Keine Residenz erforderlich, um vom Satz zu profitieren.",
      descriptionEN: "Highly relevant for freelancers/nomads: individual entrepreneurs with Small Business Status pay just 1% on turnover. No residency required to benefit from the rate.",
      backgroundDE: "Definition „georgische Quelle\" und die DBA-Lage mit Deutschland sind im Einzelfall zu prüfen; Georgien hat KEIN DBA mit DE. Für Agrotourismus liegt die Schwelle bei 700.000 GEL.",
      backgroundEN: "The definition of \"Georgian source\" and the treaty position with Germany must be checked case by case; Georgia has NO treaty with Germany. For agritourism the threshold is 700,000 GEL.",
    },
    {
      countrySlug: "mt", slug: "grp-mt", nameDE: "Global Residence Programme (Malta)", nameEN: "Global Residence Programme (Malta)",
      flatRate: 0.15, durationYears: 99,
      qualifications: ["Kauf einer qualifizierten Immobilie ≥ 275.000 € (Malta) / 220.000 € (Gozo)", "Oder Miete ≥ 9.600 €/Jahr (Malta) / 8.750 €/Jahr (Gozo)", "Nicht-EU-/EWR-Staatsangehörige ohne freien Aufenthaltsanspruch in Malta"],
      conditionsDE: "15 % Flat Tax auf Auslandseinkommen, das nach Malta überwiesen wird (Remittance-Basis). Mindeststeuer: 15.000 €/Jahr. Nicht überwiesenes Auslandseinkommen bleibt unbesteuert.",
      conditionsEN: "15% flat tax on foreign income remitted to Malta (remittance basis). Minimum annual tax: €15,000. Foreign income not remitted stays untaxed.",
      validFrom: new Date("2014-01-01"), sourceUrl: "https://cfr.gov.mt", sourceDE: "Malta Commissioner for Revenue (CFR), GRP Rules 2013",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Gilt für Nicht-EU-/EWR-Bürger; EU-Bürger nutzen das Ordinary Residence Programme (ORP). Mindeststeuer 15.000 €/Jahr. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "For non-EU/EEA nationals; EU nationals use the Ordinary Residence Programme (ORP). Minimum tax €15,000/year. Not binding advice, not tax counsel.",
      descriptionDE: "Maltesisches Residenzprogramm mit pauschaler 15 %-Besteuerung des nach Malta überwiesenen Auslandseinkommens, kombiniert mit dem Non-Dom-Remittance-Prinzip.",
      descriptionEN: "Maltese residence programme with a flat 15% tax on foreign income remitted to Malta, combined with the non-dom remittance principle.",
      backgroundDE: "Non-Domiciled-Residenten zahlen generell nur auf nach Malta überwiesene Auslandseinkünfte. Mindeststeuerbeträge und Immobilien-/Mietschwellen sind regelmäßig zu verifizieren (CFR Malta).",
      backgroundEN: "Non-domiciled residents are generally taxed only on foreign income remitted to Malta. Minimum-tax amounts and property/rent thresholds should be verified regularly (CFR Malta).",
    },
    {
      countrySlug: "mt", slug: "highly-skilled-mt", nameDE: "Highly Skilled / HQP-Regime (Malta)", nameEN: "Highly Skilled / HQP Regime (Malta)",
      flatRate: 0.15, durationYears: 5,
      qualifications: ["Qualifizierter Arbeitsvertrag in einem „eligible office\"", "Branchen: Finanzdienstleistungen (MFSA), Online-Gaming (MGA), Luftfahrt (Transport Malta)", "Mindestvergütung 65.000 € (HSI-Regime 2026, LN 20/2026; +10.000 € alle 5 Jahre)"],
      conditionsDE: "15 % Pauschalsatz auf qualifizierte Erwerbseinkünfte, bis max. 7 Mio. € (darüber zum Normaltarif). Für EWR-/Schweizer Bürger bis zu 5 aufeinanderfolgende Jahre, für Drittstaatler bis zu 4.",
      conditionsEN: "15% flat rate on qualifying employment income, up to max. €7m (excess at ordinary rates). Up to 5 consecutive years for EEA/Swiss nationals, up to 4 for third-country nationals.",
      validFrom: new Date("2026-01-01"), sourceUrl: "https://mtca.gov.mt/personal-tax/legal-and-technical/test/tax-guidelines-on-highly-qualified-persons-rules", sourceDE: "Malta Tax & Customs Administration; Tax Treatment of Highly Skilled Individuals Rules (LN 20/2026)",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Die alten HQP Rules erhielten keine Bestimmungen mehr nach dem 31.12.2025; ab 1.1.2026 gilt das konsolidierte „Highly Skilled Individuals\"-Regime (15 %, bis 31.12.2040). Werte vor Antrag amtlich bestätigen. Keine verbindliche Auskunft.",
      disclaimerEN: "The old HQP Rules issue no determinations after 31 Dec 2025; from 1 Jan 2026 the consolidated \"Highly Skilled Individuals\" regime applies (15%, until 31 Dec 2040). Confirm figures officially before applying. Not binding advice.",
      descriptionDE: "Pauschale 15 %-Besteuerung qualifizierter Fach- und Führungskräfte in eng definierten Branchen (Finanz, Gaming, Luftfahrt) — gedacht, um Spitzentalente nach Malta zu holen.",
      descriptionEN: "Flat 15% taxation of qualifying senior professionals in tightly defined sectors (financial services, gaming, aviation) — designed to attract top talent to Malta.",
      backgroundDE: "2026 konsolidiert: Die bisherigen HQP Rules werden durch die „Highly Skilled Individuals Rules\" (LN 20/2026) abgelöst, gültig bis Ende 2040. Branchenliste und Mindestvergütung werden jährlich angepasst.",
      backgroundEN: "Consolidated in 2026: the former HQP Rules are superseded by the \"Highly Skilled Individuals Rules\" (LN 20/2026), valid through end-2040. Sector list and minimum remuneration are adjusted annually.",
    },
    {
      countrySlug: "sg", slug: "nor-sg", nameDE: "Territoriale Besteuerung / NOR (Singapur)", nameEN: "Territorial Taxation / NOR (Singapore)",
      flatRate: 0.10, durationYears: 5,
      qualifications: ["Im Kern territoriale Besteuerung: Auslandseinkünfte meist steuerfrei, sofern nicht nach SG überwiesen", "NOR-Schema: Status musste vor YA 2021 gewährt sein", "Niedrige progressive Sätze auf lokales Einkommen"],
      conditionsDE: "Singapur besteuert im Wesentlichen territorial; ausländische Einkünfte meist steuerfrei, sofern nicht nach SG überwiesen. Das NOR-Schema (anteilige Besteuerung nach Arbeitstagen) ist ab YA 2021 eingestellt — keine neuen Anträge.",
      conditionsEN: "Singapore taxes largely territorially; foreign income mostly tax-free unless remitted to SG. The NOR scheme (time-apportioned taxation) is discontinued from YA 2021 — no new applications.",
      validFrom: new Date("2002-01-01"),
      sourceUrl: "https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-residency-and-tax-rates/individual-income-tax-rates",
      sourceDE: "IRAS Singapore 2025 (NOR scheme archived from YA 2021)",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "⚠ NOR ist ab YA 2021 eingestellt; nur Altfälle (Status ≤ YA 2020) profitieren noch. Die territoriale Besteuerung gilt fort. Remittance-Regeln im Einzelfall prüfen. Keine verbindliche Auskunft.",
      disclaimerEN: "⚠ NOR is discontinued from YA 2021; only legacy holders (status ≤ YA 2020) still benefit. Territorial taxation continues. Check remittance rules case by case. Not binding advice.",
      descriptionDE: "Singapurs Steuersystem ist überwiegend territorial: lokal erzieltes Einkommen wird (niedrig progressiv) besteuert, nicht überwiesenes Auslandseinkommen meist nicht.",
      descriptionEN: "Singapore's system is largely territorial: locally sourced income is taxed (low progressive rates), foreign income not remitted is mostly untaxed.",
      backgroundDE: "Das frühere NOR-Schema bot eine Zeitaufteilung für mobile Führungskräfte (>90 Tage außerhalb SG, Einkommen > SGD 160.000). Es ist ausgelaufen; der angezeigte Satz (10 %) bezieht sich auf das Alt-NOR.",
      backgroundEN: "The former NOR scheme offered time-apportionment for mobile executives (>90 days outside SG, income > SGD 160,000). It has lapsed; the displayed rate (10%) refers to the legacy NOR.",
    },
    {
      countrySlug: "it", slug: "impatriate-it", nameDE: "Regime Impatriati (Italien)", nameEN: "Impatriate Regime (Italy)",
      flatRate: 0.50, durationYears: 5,
      qualifications: ["In den letzten 3 Jahren kein IT-Wohnsitz (6–7 Jahre bei Rückkehr zum selben Arbeitgeber/Konzern)", "Hohe Qualifikation/Spezialisierung (ISTAT-Level 1–3, meist ≥ 3 Jahre Hochschule)", "Echter Wohnsitzwechsel + Bindungszusage (Clawback bei frühem Wegzug)"],
      conditionsDE: "50 % Steuerbefreiung auf qualifizierende IT-Erwerbs-/Selbstständigeneinkünfte (60 % bei minderjährigem Kind), gedeckelt auf 600.000 €/Jahr, für 5 Jahre (i. d. R. nicht verlängerbar). Davor 70 %/90 % (Süden) — abgeschafft.",
      conditionsEN: "50% tax exemption on qualifying IT employment/self-employment income (60% with a minor child), capped at €600,000/yr, for 5 years (generally non-renewable). Previously 70%/90% (South) — abolished.",
      validFrom: new Date("2024-01-01"),
      sourceUrl: "https://www.agenziaentrate.gov.it",
      sourceDE: "Agenzia delle Entrate, D.Lgs. n. 209/2023",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Clawback (rückwirkende Vollbesteuerung + Zinsen) bei zu frühem Wegzug. Der angezeigte Wert (50 %) ist die Befreiungsquote, kein Steuersatz — der Vergleichswert ist eine grobe Näherung. Keine verbindliche Auskunft.",
      disclaimerEN: "Clawback (retroactive full taxation + interest) if you leave too early. The displayed value (50%) is the exemption rate, not a tax rate — the comparison figure is a rough approximation. Not binding advice.",
      descriptionDE: "„Brain gain\"-Regime: befreit die Hälfte (bzw. 60 %) des qualifizierten italienischen Erwerbseinkommens von der IRPEF, um hochqualifizierte Rückkehrer und Zuzügler zu gewinnen.",
      descriptionEN: "\"Brain gain\" regime: exempts half (or 60%) of qualifying Italian employment income from IRPEF to attract high-skill returnees and inbound talent.",
      backgroundDE: "Daneben existiert eine Lump-Sum-Flat-Tax für HNWI auf ausländische Einkünfte: 200.000 €/Jahr (Steuerjahr 2025; davor 100.000 €), ab 1.1.2026 auf 300.000 € für Neuzuzügler erhöht (Familienmitglieder 50.000 €). Italienische Einkünfte bleiben progressiv (23–43 %).",
      backgroundEN: "Alongside it is a lump-sum flat tax for HNWIs on foreign income: €200,000/yr (tax year 2025; previously €100,000), raised to €300,000 for new arrivals from 1 Jan 2026 (family members €50,000). Italian income stays progressive (23–43%).",
    },
    {
      countrySlug: "gb", slug: "fig-gb", nameDE: "FIG-Regime (Vereinigtes Königreich)", nameEN: "FIG Regime (United Kingdom)",
      flatRate: 0.00, durationYears: 4,
      qualifications: ["In den letzten 10 zusammenhängenden Jahren nicht UK-ansässig", "Auf den 6.4.2025 weniger als 4 Jahre UK-ansässig (für Übergang)", "Jährliche Antragstellung (claim)"],
      conditionsDE: "Neuzuzügler zahlen in den ersten 4 Steuerjahren keine UK-Steuer auf ausländische Einkünfte und Gewinne (auch wenn ins UK gebracht). UK-Quelleneinkünfte werden normal besteuert. Das Non-Dom-/Remittance-Regime wurde zum 6.4.2025 abgeschafft.",
      conditionsEN: "New arrivals pay no UK tax on foreign income and gains in the first 4 tax years (even if brought into the UK). UK-source income is taxed normally. The non-dom/remittance regime was abolished on 6 Apr 2025.",
      validFrom: new Date("2025-04-06"), sourceUrl: "https://www.gov.uk/guidance/check-if-you-can-claim-the-4-year-foreign-income-and-gains-regime", sourceDE: "HMRC, 4-Year Foreign Income and Gains (FIG) Regime (from 6 April 2025)",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Wer FIG beansprucht, verliert für das Jahr den persönlichen Steuerfreibetrag (Personal Allowance) und den CGT-Freibetrag. Tax cliff nach 4 Jahren (volle Welteinkommensbesteuerung). IHT auf Weltvermögen ab 10 Jahren Ansässigkeit. Der angezeigte Satz (0 %) gilt NUR für Auslandseinkünfte, nicht für UK-Gehalt. Keine verbindliche Auskunft.",
      disclaimerEN: "⚠ Claiming FIG forfeits the personal allowance and the CGT annual exempt amount for that year. Tax cliff after 4 years (full worldwide taxation). IHT on worldwide assets from 10 years of residence. The displayed rate (0%) applies ONLY to foreign income, not UK salary. Not binding advice.",
      descriptionDE: "Ersatz für das zum 6.4.2025 abgeschaffte Non-Dom-/Remittance-Regime: vier steuerfreie Jahre für ausländische Einkünfte und Gewinne neu zugezogener UK-Residenten.",
      descriptionEN: "Replacement for the non-dom/remittance regime abolished on 6 Apr 2025: four tax-free years on foreign income and gains for newly arrived UK residents.",
      backgroundDE: "Das Non-Dom-Regime endete nach über 200 Jahren. Für Alt-Non-Doms gibt es Übergangsregeln (Temporary Repatriation Facility, Rebasing). Der Vergleichswert im Rechner ist irreführend für Personen mit UK-Gehalt — siehe Detailbedingungen.",
      backgroundEN: "The non-dom regime ended after more than 200 years. Transitional rules exist for former non-doms (Temporary Repatriation Facility, rebasing). The calculator comparison is misleading for people with UK salary — see detailed conditions.",
    },
    {
      countrySlug: "fr", slug: "impatries-fr", nameDE: "Régime des impatriés (Frankreich)", nameEN: "Impatriate Regime (France)",
      flatRate: 0.30, durationYears: 8,
      qualifications: ["Aus dem Ausland angeworben/entsandt", "In den 5 Kalenderjahren vor Amtsantritt nicht in FR steuerlich ansässig", "Verlegung des Steuerwohnsitzes nach FR ab Amtsantritt"],
      conditionsDE: "Befreiung der Impatriierungs-Prämie (prime d'impatriation) von der ESt — entweder in tatsächlicher Höhe oder pauschal mit 30 % der Gesamtvergütung; zusätzlich 50 % Befreiung bestimmter passiver Auslandseinkünfte. Bis Ende des 8. Kalenderjahres nach Amtsantritt.",
      conditionsEN: "Exemption of the impatriation bonus (prime d'impatriation) from income tax — either at its actual amount or a flat 30% of total remuneration; plus 50% exemption of certain passive foreign income. Until end of the 8th calendar year after taking up duties.",
      validFrom: new Date("2008-01-01"), sourceUrl: "https://www.impots.gouv.fr/international-particulier/le-regime-des-impatries", sourceDE: "impots.gouv.fr; Art. 155 B CGI; BOI-RSA-GEO-40-10 (akt. 11.8.2025)",
      riskLevel: "low", requiresLegalAdvice: true,
      disclaimerDE: "Die 30 %-Pauschale ist eine Wahloption für die Prämie, kein Steuersatz auf das Gesamteinkommen — der Rechner-Vergleichswert ist nur eine grobe Annäherung. Genaue Quoten/Bedingungen vor Antrag bei impots.gouv.fr prüfen. Keine verbindliche Auskunft.",
      disclaimerEN: "The 30% flat option applies to the bonus, not as a tax rate on total income — the calculator comparison is only a rough approximation. Verify exact quotas/conditions before applying at impots.gouv.fr. Not binding advice.",
      descriptionDE: "Steuervergünstigung für aus dem Ausland angeworbene Arbeitnehmer/Führungskräfte: ein Teil der Vergütung (die Impatriierungs-Prämie) sowie Teile passiver Auslandseinkünfte werden zeitlich befristet von der Einkommensteuer befreit.",
      descriptionEN: "Tax break for employees/executives recruited from abroad: part of the remuneration (the impatriation bonus) plus parts of passive foreign income are exempt from income tax for a limited period.",
      backgroundDE: "Geregelt in Art. 155 B CGI; die Finanzverwaltung aktualisierte die Auslegung am 11.8.2025 (BOI-RSA-GEO-40-10). Beispiel: Amtsantritt 1.1.2025 → Begünstigung bis 31.12.2033. Auch Sozialabgaben-Erleichterungen möglich.",
      backgroundEN: "Governed by Art. 155 B CGI; the tax administration updated its guidance on 11 Aug 2025 (BOI-RSA-GEO-40-10). Example: start 1 Jan 2025 → benefit until 31 Dec 2033. Social-contribution reliefs may also apply.",
    },
    {
      countrySlug: "at", slug: "zuzug-at", nameDE: "Zuzugsbegünstigung (§ 103 EStG, Österreich)", nameEN: "Relocation Relief (§103 EStG, Austria)",
      flatRate: 0.30, durationYears: 5,
      qualifications: ["Zuzug aus dem Ausland (Verlagerung des Lebensmittelpunkts nach AT)", "Zuzugsfreibetrag nur für Wissenschaftler/Forscher", "Beseitigung steuerlicher Mehrbelastung: Personen im öffentlichen Interesse (Ermessen des BMF)"],
      conditionsDE: "Zwei Komponenten: (1) Beseitigung der durch den Zuzug entstehenden steuerlichen Mehrbelastung bei Auslandseinkünften (Ermessen des BMF); (2) Zuzugsfreibetrag von 30 % der Einkünfte aus wissenschaftlicher Tätigkeit (nur Wissenschaftler/Forscher), bescheidmäßig für 5 Jahre.",
      conditionsEN: "Two components: (1) elimination of the additional tax burden on foreign income arising from relocation (at the BMF's discretion); (2) a relocation allowance of 30% of income from scientific activity (researchers only), granted by ruling for 5 years.",
      validFrom: new Date("2016-01-01"), sourceUrl: "https://www.bmf.gv.at/themen/steuern/arbeitnehmerveranlagung/zuzugsbeguenstigung.html", sourceDE: "BMF Österreich, § 103 EStG 1988",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "Der Zuzugsfreibetrag (30 %) gilt nur für wissenschaftliche Einkünfte und ist keine pauschale Steuer aufs Gesamteinkommen — der Rechner-Vergleichswert ist nur eine grobe Annäherung. Die Mehrbelastungs-Beseitigung ist eine Ermessensentscheidung. Keine verbindliche Auskunft.",
      disclaimerEN: "The relocation allowance (30%) applies only to scientific income and is not a flat tax on total income — the calculator comparison is only a rough approximation. The burden-elimination is a discretionary decision. Not binding advice.",
      descriptionDE: "Auf Antrag beim BMF: Erleichterung der steuerlichen Mehrbelastung bei Zuzug, v. a. für Wissenschaftler/Forscher und Personen, deren Zuzug im öffentlichen Interesse liegt.",
      descriptionEN: "On application to the BMF: relief from the additional tax burden on relocation, primarily for scientists/researchers and persons whose relocation is in the public interest.",
      backgroundDE: "Ein „Zuzug\" i. S. d. § 103 EStG setzt die Verlagerung des Mittelpunkts der Lebensinteressen nach Österreich voraus (vom VwGH präzisiert). Der Zuzugsfreibetrag wird bescheidmäßig für 5 Jahre zuerkannt.",
      backgroundEN: "A \"relocation\" under §103 EStG requires shifting one's centre of vital interests to Austria (clarified by the VwGH). The relocation allowance is granted by ruling for 5 years.",
    },
    {
      countrySlug: "ch", slug: "lump-sum-ch", nameDE: "Pauschalbesteuerung / Besteuerung nach Aufwand (Schweiz)", nameEN: "Lump-Sum Taxation / Expenditure-Based (Switzerland)",
      flatRate: 0.00, durationYears: 99,
      qualifications: ["Ausländer ohne Erwerbstätigkeit in der Schweiz", "Erstmaliger oder erneuter Zuzug in die Schweiz", "Kantonal unterschiedlich; in ZH, SH, AR, BL, BS abgeschafft"],
      conditionsDE: "Besteuerung nach dem Lebensaufwand statt nach Einkommen/Vermögen. Bemessung = der höhere Wert aus 7-facher Jahresmiete, dem tatsächlichen Aufwand oder dem Bundes-Mindestbetrag (CHF 434.700 für 2025; CHF 435.000 für 2026). 21 von 26 Kantonen bieten das Regime an.",
      conditionsEN: "Taxation by living expenditure instead of income/wealth. Base = the higher of 7× annual rent, actual expenditure, or the federal minimum (CHF 434,700 for 2025; CHF 435,000 for 2026). 21 of 26 cantons offer the regime.",
      validFrom: new Date("2016-01-01"), sourceUrl: "https://www.efd.admin.ch/en/lump-sum-taxation", sourceDE: "Eidg. Finanzdepartement (EFD) / ESTV; kantonale Steuerämter",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "Keine prozentuale Steuer auf Einkommen — der angezeigte Satz (0 %) ist ein Platzhalter; die Steuer bemisst sich am Lebensaufwand (Mindestbasis CHF ~435.000). Zürich, Schaffhausen, Appenzell A.Rh., Basel-Land und Basel-Stadt bieten das Regime NICHT an. Kantonale Mindestwerte vor Antrag prüfen. Keine verbindliche Auskunft.",
      disclaimerEN: "No percentage tax on income — the displayed rate (0%) is a placeholder; tax is assessed on living expenditure (minimum base ~CHF 435,000). Zurich, Schaffhausen, Appenzell A.Rh., Basel-Landschaft and Basel-Stadt do NOT offer the regime. Check cantonal minimums before applying. Not binding advice.",
      descriptionDE: "HNWI-Regime: Statt nach Einkommen/Vermögen wird nach dem Lebensaufwand besteuert (Mindestbemessung, oft an die 7-fache Jahresmiete gekoppelt). Nur für nicht in der Schweiz erwerbstätige Ausländer.",
      descriptionEN: "HNWI regime: taxed on living expenditure rather than income/wealth (minimum base, often tied to 7× annual rent). Only for foreigners not gainfully employed in Switzerland.",
      backgroundDE: "Kantonal sehr unterschiedlich; fünf Deutschschweizer Kantone haben das Regime zwischen 2010 und 2014 abgeschafft (vier per Volksabstimmung, Basel-Stadt parlamentarisch). Französisch „forfait fiscal\", italienisch „tassazione secondo il dispendio\".",
      backgroundEN: "Highly canton-dependent; five German-speaking cantons abolished it between 2010 and 2014 (four by popular vote, Basel-Stadt by parliament). French \"forfait fiscal\", Italian \"tassazione secondo il dispendio\".",
    },
    {
      countrySlug: "th", slug: "ltr-th", nameDE: "LTR-Visum + Remittance-Regel (Thailand)", nameEN: "LTR Visa + Remittance Rule (Thailand)",
      flatRate: 0.00, durationYears: 10,
      qualifications: ["Steuerresident bei ≥ 183 Tagen/Jahr in Thailand", "LTR-Visum-Kategorie (z. B. Wealthy Global Citizen, Wealthy Pensioner, Work-From-Thailand Professional)", "Qualifizierende Auslandseinkünfte je nach Kategorie"],
      conditionsDE: "Thailand besteuert Residenten auf ins Land überwiesene Auslandseinkünfte (Regeländerung ab 1.1.2024). Bestimmte LTR-Kategorien sind von der Steuer auf überwiesene Auslandseinkünfte befreit. Vor 2024 erzielte Einkünfte bleiben bei Überweisung steuerfrei.",
      conditionsEN: "Thailand taxes residents on foreign income remitted into the country (rule change from 1 Jan 2024). Certain LTR categories are exempt from tax on remitted foreign income. Income earned before 2024 remains tax-free when remitted.",
      validFrom: new Date("2024-01-01"), sourceUrl: "https://ltr.boi.go.th", sourceDE: "Thai Revenue Department; Board of Investment (BOI), LTR-Visum",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Keine pauschale Befreiung für alle LTR-Inhaber — jede Kategorie hat eigene Kriterien und Reichweite. Die Remittance-Auslegung wurde 2024 verschärft; aktuelle Praxis (auch mögliche Lockerungen) vor Umzug prüfen. Der angezeigte Satz (0 %) gilt nur für qualifizierte LTR-Kategorien. Keine verbindliche Auskunft.",
      disclaimerEN: "⚠ No blanket exemption for all LTR holders — each category has its own criteria and scope. The remittance interpretation was tightened in 2024; check current practice (including possible relaxations) before relocating. The displayed rate (0%) applies only to qualifying LTR categories. Not binding advice.",
      descriptionDE: "Thailand besteuert nach dem Remittance-Prinzip: nur ins Land gebrachte Auslandseinkünfte sind steuerpflichtig. Das LTR-Langzeitvisum bietet für bestimmte Kategorien eine Befreiung auf Auslandseinkommen.",
      descriptionEN: "Thailand taxes on a remittance basis: only foreign income brought into the country is taxable. The LTR long-term visa offers an exemption on foreign income for certain categories.",
      backgroundDE: "Relevant für Bangkok und Chiang Mai. Die Verschärfung 2024 beendete die frühere Praxis, Auslandseinkünfte durch verzögerte Überweisung steuerfrei zu halten. LTR-Kategorien/Bedingungen über BOI prüfen.",
      backgroundEN: "Relevant for Bangkok and Chiang Mai. The 2024 tightening ended the earlier practice of keeping foreign income tax-free via delayed remittance. Check LTR categories/conditions via the BOI.",
    },
    {
      countrySlug: "pl", slug: "ulga-powrot-pl", nameDE: "Rückkehrer-Entlastung (Ulga na powrót, Polen)", nameEN: "Return Relief (Ulga na powrót, Poland)",
      flatRate: 0.00, durationYears: 4,
      qualifications: ["Verlegung des Steuerwohnsitzes nach Polen nach dem 31.12.2021", "In den 3 vorangegangenen Kalenderjahren kein PL-Steuerresident", "Qualifizierende PL-Einkünfte (Anstellung/Gewerbe); Nachweis des Auslandswohnsitzes"],
      conditionsDE: "ESt-Befreiung von bis zu 85.528 PLN pro Jahr für 4 aufeinanderfolgende Steuerjahre. Mit dem allgemeinen Freibetrag (30.000 PLN) effektiv bis ~115.528 PLN/Jahr steuerfrei. Gilt auch für Personen, die nie zuvor in Polen lebten.",
      conditionsEN: "Income-tax exemption of up to PLN 85,528 per year for 4 consecutive tax years. Combined with the general allowance (PLN 30,000) effectively up to ~PLN 115,528/yr tax-free. Also applies to people who never lived in Poland before.",
      validFrom: new Date("2022-01-01"), sourceUrl: "https://www.podatki.gov.pl", sourceDE: "Ministerstwo Finansów (Polnisches Finanzministerium), Ulga na powrót",
      riskLevel: "low", requiresLegalAdvice: false,
      disclaimerDE: "Die Entlastung ist ein jährlicher Freibetrag (max. 85.528 PLN), kein Steuersatz — der Rechner-Vergleichswert (0 %) ist nur eine grobe Annäherung. Der Steuerpflichtige wählt das Startjahr (Zuzugsjahr oder Folgejahr). Daneben existieren Lump-Sum auf Auslandseinkommen und IP-Box. Keine verbindliche Auskunft.",
      disclaimerEN: "The relief is an annual allowance (max PLN 85,528), not a tax rate — the calculator comparison (0%) is only a rough approximation. The taxpayer chooses the start year (arrival year or the next). A lump-sum on foreign income and an IP-Box also exist. Not binding advice.",
      descriptionDE: "Steueranreiz für Personen, die ihren Steuerwohnsitz nach mindestens 3 Jahren im Ausland nach Polen (zurück) verlegen: vier Jahre lang ein hoher jährlicher Einkommensteuer-Freibetrag.",
      descriptionEN: "Tax incentive for people who move their tax residence to Poland after at least 3 years abroad: a high annual income-tax allowance for four years.",
      backgroundDE: "Eingeführt 2022. Daneben gibt es eine Lump-Sum-Besteuerung auf Auslandseinkommen neuer Residenten und die IP-Box für IP-Einkünfte. Höchstbeträge sind jährlich zu verifizieren.",
      backgroundEN: "Introduced in 2022. Alongside it are a lump-sum tax on new residents' foreign income and the IP-Box for IP income. Maximum amounts should be verified annually.",
    },
];

export const exitRuleDefs = [
    {
      slug: "exit-tax-6-astg", ruleType: "exit_tax", legalRef: "§ 6 AStG", sortOrder: 0,
      nameDE: "Wegzugsbesteuerung (§ 6 AStG)", nameEN: "Exit Taxation (§6 AStG)",
      descriptionDE: "Bei Wegzug ins Ausland gelten wesentliche Beteiligungen (≥ 1 % an Kapitalgesellschaften) sowie seit dem 1.1.2025 bestimmte Investmentfondsanteile als fiktiv veräußert — die stillen Reserven werden besteuert, ohne dass tatsächlich verkauft wurde.",
      descriptionEN: "On relocating abroad, significant shareholdings (≥1% in corporations) and, since 1 Jan 2025, certain investment-fund units are treated as deemed sold — the unrealised gains are taxed even though nothing was actually sold.",
      affectedDE: "Personen mit GmbH-/AG-Anteilen ≥ 1 % (o. Ä.), die in mindestens 7 der letzten 12 Jahre unbeschränkt steuerpflichtig waren. Seit 2025 zusätzlich Investmentfondsanteile mit ≥ 1 % Beteiligung ODER Anschaffungskosten ≥ 500.000 €.",
      affectedEN: "People holding ≥1% in a GmbH/AG (or similar) who were subject to unlimited tax liability for at least 7 of the last 12 years. Since 2025 also investment-fund units with a ≥1% holding OR acquisition cost ≥ €500,000.",
      backgroundDE: "Erleichterung: Stundung in 7 gleichen Jahresraten möglich (i. d. R. nur gegen Sicherheitsleistung und Mitwirkungspflichten); die frühere zinslose EU/EWR-Stundung entfiel mit der Reform. Rückkehrerregelung: Bei Rückkehr binnen 7 Jahren kann die Steuer rückwirkend entfallen (Anteile dürfen nicht veräußert/übertragen werden).",
      backgroundEN: "Relief: deferral in 7 equal annual installments is possible (usually only against collateral and cooperation duties); the former interest-free EU/EEA deferral was removed with the reform. Return rule: returning within 7 years can retroactively cancel the tax (shares must not be sold/transferred).",
      sourceUrl: "https://www.gesetze-im-internet.de/astg/__6.html", sourceDE: "§ 6 AStG (gesetze-im-internet.de); BMF, Wegzugsbesteuerung 2025",
      riskLevel: "high", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Greift ohne tatsächlichen Verkauf — kann zu erheblicher Steuerlast ohne Liquiditätszufluss führen. Steuerberater zwingend. Schwellen und Stundungsmodalitäten nach jüngster Reform individuell prüfen. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "⚠ Triggers without an actual sale — can create a substantial tax burden with no cash inflow. A tax advisor is essential. Verify thresholds and deferral terms after the latest reform individually. Not binding advice, not tax counsel.",
    },
    {
      slug: "extended-limited-2-astg", ruleType: "extended_limited_liability", legalRef: "§ 2 AStG", sortOrder: 1,
      nameDE: "Erweiterte beschränkte Steuerpflicht (§ 2 AStG)", nameEN: "Extended Limited Tax Liability (§2 AStG)",
      descriptionDE: "Bei Wegzug in ein Niedrigsteuerland mit fortbestehenden wesentlichen wirtschaftlichen Interessen in Deutschland bleiben bestimmte deutsche Einkünfte für das Wegzugsjahr und die folgenden 10 Jahre erweitert steuerpflichtig.",
      descriptionEN: "On moving to a low-tax country while retaining substantial economic interests in Germany, certain German-source income remains subject to extended taxation for the year of departure and the following 10 years.",
      affectedDE: "Deutsche Staatsangehörige, die in den letzten 10 Jahren vor Wegzug mindestens 5 Jahre unbeschränkt steuerpflichtig waren, in ein Niedrigsteuergebiet ziehen und wesentliche wirtschaftliche Interessen in DE behalten (z. B. ≥ 1 % an einer dt. Kapitalgesellschaft, oder > 30 % bzw. > 62.000 € nicht-ausländische Einkünfte).",
      affectedEN: "German nationals who were subject to unlimited tax liability for at least 5 of the 10 years before departure, move to a low-tax territory, and keep substantial economic interests in Germany (e.g. ≥1% in a German corporation, or >30% / >€62,000 of non-foreign income).",
      backgroundDE: "Die Niedrigsteuer-Definition und der betroffene Einkünftekatalog (insbesondere Kapitaleinkünfte) sind im Einzelfall zu prüfen. Wirkt zusätzlich zur normalen beschränkten Steuerpflicht.",
      backgroundEN: "The low-tax definition and the catalogue of affected income (notably capital income) must be checked case by case. Applies on top of ordinary limited tax liability.",
      sourceUrl: "https://www.gesetze-im-internet.de/astg/__2.html", sourceDE: "§ 2 AStG (gesetze-im-internet.de)",
      riskLevel: "high", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Gilt bis zu 10 Jahre nach Wegzug auch ohne Anwesenheit in Deutschland. Niedrigsteuer-Einstufung des Ziellands entscheidend. Steuerberater erforderlich. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "⚠ Applies for up to 10 years after departure, even without presence in Germany. The destination's low-tax classification is decisive. A tax advisor is required. Not binding advice, not tax counsel.",
    },
    {
      slug: "dba-status", ruleType: "dba_status", legalRef: null, sortOrder: 2,
      nameDE: "DBA-Status / Länder ohne DBA", nameEN: "Tax-Treaty Status / Countries without a Treaty",
      descriptionDE: "Doppelbesteuerungsabkommen (DBA) entscheiden, welcher Staat welche Einkünfte besteuern darf. Ohne aktives DBA fehlt der Schutz vor Doppelbesteuerung — das Risiko einer doppelten Belastung steigt erheblich.",
      descriptionEN: "Double-taxation treaties (DTTs) determine which state may tax which income. Without an active treaty there is no protection from double taxation — the risk of being taxed twice rises substantially.",
      affectedDE: "Alle Wegziehenden — entscheidend ist das jeweilige Zielland. Kein aktives DBA besteht z. B. mit den VAE (seit 2021). Pro Zielland ist DBA ja/nein samt Kernpunkten zu prüfen.",
      affectedEN: "Everyone relocating — the destination country is decisive. There is no active treaty with the UAE (since 2021), for example. For each destination, treaty yes/no and its key points should be checked.",
      backgroundDE: "Der DBA-Status ist laufend aus der BMF-DBA-Übersicht zu pflegen, da sich Abkommen ändern, auslaufen oder neu in Kraft treten.",
      backgroundEN: "Treaty status must be maintained continuously from the BMF treaty overview, as treaties change, lapse, or newly enter into force.",
      sourceUrl: "https://www.bundesfinanzministerium.de/Content/DE/Standardartikel/Themen/Steuern/Internationales_Steuerrecht/Staatenbezogene_Informationen/staatenbezogene_info.html", sourceDE: "BMF, Übersicht der Doppelbesteuerungsabkommen",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Besonders riskant bei Ländern ohne aktives DBA (z. B. VAE). Status und Kernregeln pro Zielland verifizieren. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "⚠ Especially risky for countries without an active treaty (e.g. the UAE). Verify status and key rules per destination. Not binding advice, not tax counsel.",
    },
    {
      slug: "fbar-fatca-us", ruleType: "reporting", legalRef: "FBAR / FATCA", sortOrder: 3,
      nameDE: "USA-Spezifika: FBAR / FATCA", nameEN: "US Specifics: FBAR / FATCA",
      descriptionDE: "Wer in die USA zieht oder US-Konten hält, unterliegt FBAR-Meldepflichten (Meldung ausländischer Konten ab einem Gesamtwert von 10.000 USD) und FATCA. US-Staatsbürger unterliegen zusätzlich der weltweiten Steuerpflicht (mit FEIE / Foreign Tax Credit).",
      descriptionEN: "Anyone moving to the US or holding US accounts is subject to FBAR reporting (foreign accounts above an aggregate of USD 10,000) and FATCA. US citizens are additionally subject to worldwide taxation (with FEIE / Foreign Tax Credit).",
      affectedDE: "Nach USA Zuziehende, Personen mit US-Konten sowie US-Staatsbürger und Greencard-Inhaber (unabhängig vom Wohnsitz).",
      affectedEN: "People moving to the US, holders of US accounts, and US citizens and green-card holders (regardless of residence).",
      backgroundDE: "FBAR wird elektronisch beim FinCEN (Formular 114) eingereicht; FATCA betrifft u. a. das Formular 8938. Schwellen und Formulare ändern sich — vor dem Umzug bei der IRS prüfen.",
      backgroundEN: "FBAR is filed electronically with FinCEN (Form 114); FATCA involves Form 8938 among others. Thresholds and forms change — check with the IRS before relocating.",
      sourceUrl: "https://www.irs.gov/businesses/small-businesses-self-employed/report-of-foreign-bank-and-financial-accounts-fbar", sourceDE: "IRS — Report of Foreign Bank and Financial Accounts (FBAR); FATCA",
      riskLevel: "medium", requiresLegalAdvice: true,
      disclaimerDE: "⚠ Versäumte FBAR/FATCA-Meldungen können empfindliche Strafen auslösen. Schwellen und Formulare vor dem Umzug amtlich prüfen. Keine verbindliche Auskunft, keine Steuerberatung.",
      disclaimerEN: "⚠ Missed FBAR/FATCA filings can trigger severe penalties. Verify thresholds and forms officially before relocating. Not binding advice, not tax counsel.",
    },
];
